npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: false
    npmAuthIdent: "username:password"
    npmAuthToken: ${GITHUB_CHRONOS_TOKEN}

npmScopes:
  arekzc:
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: ${GITHUB_CHRONOS_TOKEN}