name: Chronos Continues Integration

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - release/*
      - hotfix/*
      - support/*
      - bugfix/*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install project dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Build packages
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: Run tests
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test
    - name: Publish package
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: run publish --new-version 0.0.0-dev.$(git rev-parse --short HEAD) --skip-build
