name: Universal release packages

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - release/*
      - hotfix/*
      - support/*
      - bugfix/*
    tags:
      - '*.*.*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: 'Use Node.js 14.x'
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: 'Install dependencies'
        run: |
          yarn --immutable
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: 'Build packages'
        run: |
          yarn workspaces foreach --exclude root run build
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: 'Lint files'
        run: |
          yarn workspaces foreach --exclude root run lint
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: 'Test'
        run: |
          yarn workspaces foreach --exclude root run test
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: 'Release packages'
        run: |
          yarn workspaces foreach --exclude root version ${GITHUB_REF/refs\/tags\//}
          yarn workspaces foreach --exclude root npm publish
        shell: bash
        env:
          VERSION: ${GITHUB_REF/refs\/tags\//}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
